name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  
      
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_UN }}
          password: ${{ secrets.DOCKER_HUB_PW }}
          
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_UN }}/patient-service:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_HUB_UN }}/patient-service:${{ github.sha }}  

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region  us-east-1 --name cw-cluster
  
      - name: Deploy to EKS
        env:
            IMAGE_TAG: ${{ github.sha }}
        run: |
            kubectl set image deployment/patient-service patient-service=${{ secrets.DOCKER_HUB_UN }}/patient-service:${IMAGE_TAG}
            kubectl rollout status deployment/patient-service    
            